---
seo_meta:
  name: Cam Price
  description: Show price and item for customer
  keywords: []

# url_options:
#  host: 0.0.0.0:3000
#  protocol: http

admin:
  emails: ["eric@cloud-mes.com", "shin.php@gmail.com"]
